import "android.widget.HorizontalScrollView"
import "android.widget.LinearLayout"
import "android.widget.ListView"
import "androidx.appcompat.widget.AppCompatSpinner"
import "com.google.android.material.card.MaterialCardView"
import "com.google.android.material.textview.MaterialTextView";
import "vinx.material.textfield.MaterialTextField"
import "android.graphics.drawable.GradientDrawable"
import "android.util.TypedValue"
local getDp = lambda i : TypedValue.applyDimension(1,i,activity.getResources().getDisplayMetrics())

local surfaceColorVar=ColorUtil.ColorSurfaceVariant

return {
  LinearLayout;
  id="ll";
  orientation="vertical";
  {
    HorizontalScrollView;
    layout_marginTop="4dp";
    layout_height="56dp";
    horizontalScrollBarEnabled=false;
    {
      LinearLayout;
      layout_height="match";
      orientation="2";
      gravity = "center",
      {
        MaterialCardView;
        layout_height="48dp";
        layout_width="22%w";
        layout_margin="6dp";
        layout_gravity="center";
        id="aa";
        {
          MaterialTextView;
          text="继承关系";
          layout_gravity="center";
        };
      };
      {
        MaterialCardView;
        layout_height="48dp";
        layout_width="22%w";
        layout_margin="6dp";
        layout_gravity="center";
        id="bb";
        {
          MaterialTextView;
          text="构建方法";
          layout_gravity="center";
        };
      };
      {
        MaterialCardView;
        layout_height="48dp";
        layout_width="22%w";
        layout_margin="6dp";
        layout_gravity="center";
        id="cc";
        {
          MaterialTextView;
          text="公有方法";
          layout_gravity="center";
        };
      };
      {
        MaterialCardView;
        layout_height="48dp";
        layout_width="22%w";
        layout_margin="6dp";
        layout_gravity="center";
        id="dd";
        {
          MaterialTextView;
          text="公有事件";
          layout_gravity="center";
        };
      };
      {
        MaterialCardView;
        layout_height="48dp";
        layout_width="22%w";
        layout_margin="6dp";
        layout_gravity="center";
        id="ee";
        {
          MaterialTextView;
          text="公有字段";
          layout_gravity="center";
        };
      };
      {
        MaterialCardView;
        layout_height="48dp";
        layout_width="22%w";
        layout_margin="6dp";
        layout_gravity="center";
        id="ff";
        {
          MaterialTextView;
          text="公有setter";
          layout_gravity="center";
        };
      };
      {
        MaterialCardView;
        layout_height="48dp";
        layout_width="22%w";
        layout_margin="6dp";
        layout_gravity="center";
        id="gg";
        {
          MaterialTextView;
          text="公有getter";
          layout_gravity="center";
        };
      };
      {
        MaterialCardView;
        layout_height="48dp";
        layout_width="22%w";
        layout_margin="6dp";
        layout_gravity="center";
        id="hh";
        {
          MaterialTextView;
          text="R类资源";
          layout_gravity="center";
        };
      };
    };
  };
  {
    LinearLayout;
    orientation="2";
    layout_width="-1";
    {
      MaterialTextField,
      layout_margin="16dp",
      layout_height="wrap",
      textSize="12dp",
      singleLine=true,
      TintColor=ColorUtil.getColorPrimary(),
      style=MDC_R.style.Widget_Material3_TextInputLayout_OutlinedBox,
      id="ed",
    },
    {
      AppCompatSpinner;
      layout_marginTop="16dp",
      padding="-18dp";
      Visibility=8;
      layout_width="-1";
      id="spc";
      popupBackgroundDrawable=GradientDrawable().setShape(0).setColor(surfaceColorVar).setCornerRadius(getDp(12)),
      items={
      };
    };
    {
      AppCompatSpinner;
      layout_marginTop="16dp",
      padding="-18dp";
      Visibility=8;
      layout_width="-1";
      id="sph";
      popupBackgroundDrawable=GradientDrawable().setShape(0).setColor(surfaceColorVar).setCornerRadius(getDp(12)),
      items={
      };
    };
  };
  {
    ListView;
    FastScrollEnabled=true;
    id="li";
    DividerHeight=2;
    layout_margin="6dp",
  };
};
