{
  import "android.widget.*";
  LinearLayout;
  gravity="bottom";
  orientation="vertical";
  paddingTop="16dp";
  paddingBottom="16dp";
  paddingLeft="16dp";
  layout_width="fill";
  layout_height="160dp";
  paddingRight="16dp";
  id="heard";
  BackgroundResource=luajava.bindClass("com.eurya.luaj.R").drawable.side_nav_bar;
  {
    ImageView;
    layout_height="56dp";
    paddingTop="16dp";
    id="heard_image";
    layout_width="56dp";
    BackgroundResource=luajava.bindClass("com.eurya.luaj.R").drawable.ic_launcher;
  };
  {
    TextView;
    text="TestLuaJ";
    layout_width="match_parent";
    layout_height="wrap_content";
    paddingTop="16dp";
    textColor=0xffffffff;
    textSize="16sp";
  };
  {
    TextView;
    layout_height="wrap_content";
    id="textView";
    text="DrawerLayout@Demo";
    textColor=0xffffffff;
    layout_width="wrap_content";
  };
};