import "android.widget.LinearLayout"
import "android.widget.HorizontalScrollView"
import "android.widget.FrameLayout"
import "androidx.swiperefreshlayout.widget.SwipeRefreshLayout"
import "androidx.recyclerview.widget.RecyclerView"
import "com.google.android.material.textview.MaterialTextView"
import "com.google.android.material.chip.ChipGroup"
import "com.google.android.material.chip.Chip"
import "com.google.android.material.button.MaterialButton"
import "com.google.android.material.card.MaterialCardView"
import "vinx.material.textfield.MaterialTextField"

local ColorUtil = this.themeUtil
local primary = ColorUtil.getColorPrimary()
local onVar = ColorUtil.getColorOnSurfaceVariant()
local surfaceLow = ColorUtil.getColorSurfaceContainerLow
  and ColorUtil.getColorSurfaceContainerLow()
  or ColorUtil.getColorBackground()

local function rootChip(id, text)
  return {
    Chip,
    id = id,
    text = text,
    Checkable = true,
    CheckedIconEnabled = true,
    layout_marginEnd = "6dp",
  }
end

return {
  LinearLayout,
  orientation = "vertical",
  layout_width = "match",
  layout_height = "match",
  BackgroundColor = "?attr/colorSurface",

  {
    HorizontalScrollView,
    layout_width = "match",
    layout_height = "wrap",
    horizontalScrollBarEnabled = false,
    {
      ChipGroup,
      id = "rootChips",
      layout_width = "wrap",
      layout_height = "wrap",
      paddingLeft = "12dp",
      paddingRight = "12dp",
      paddingTop = "10dp",
      paddingBottom = "4dp",
      singleSelection = true,
      selectionRequired = true,
      rootChip("chip_all", res.string.media_root_all or "全部"),
      rootChip("chip_crash", res.string.media_root_crash or "崩溃日志"),
      rootChip("chip_backups", res.string.media_root_backups or "代码备份"),
      rootChip("chip_zip", res.string.media_root_zip or "工程 ZIP"),
    },
  },

  {
    MaterialCardView,
    layout_width = "match",
    layout_height = "wrap",
    layout_marginLeft = "12dp",
    layout_marginRight = "12dp",
    layout_marginTop = "4dp",
    layout_marginBottom = "4dp",
    cardElevation = "0dp",
    radius = "12dp",
    cardBackgroundColor = surfaceLow,
    {
      LinearLayout,
      orientation = "vertical",
      layout_width = "match",
      layout_height = "wrap",
      paddingLeft = "12dp",
      paddingRight = "8dp",
      paddingTop = "8dp",
      paddingBottom = "8dp",
      {
        LinearLayout,
        orientation = "horizontal",
        layout_width = "match",
        layout_height = "wrap",
        gravity = "center_vertical",
        {
          MaterialTextView,
          id = "pathText",
          layout_width = "0dp",
          layout_weight = 1,
          layout_height = "wrap",
          textSize = "12sp",
          textColor = onVar,
          maxLines = 2,
          text = "…",
        },
        {
          MaterialButton,
          id = "btnUp",
          text = res.string.media_up or "上级",
          layout_width = "wrap",
          layout_height = "wrap",
          minHeight = "36dp",
          textSize = "12sp",
          styleAttr = "?attr/borderlessButtonStyle",
          textColor = primary,
        },
        {
          MaterialButton,
          id = "btnRefresh",
          text = res.string.media_refresh or "刷新",
          layout_width = "wrap",
          layout_height = "wrap",
          minHeight = "36dp",
          textSize = "12sp",
          styleAttr = "?attr/borderlessButtonStyle",
          textColor = primary,
        },
      },
      {
        MaterialTextView,
        id = "metaText",
        layout_width = "match",
        layout_height = "wrap",
        layout_marginTop = "2dp",
        textSize = "11sp",
        textColor = onVar,
        text = "",
      },
    },
  },

  {
    MaterialTextField,
    id = "searchEdit",
    layout_marginLeft = "12dp",
    layout_marginRight = "12dp",
    layout_marginBottom = "2dp",
    layout_height = "wrap",
    layout_width = "match",
    textSize = "12sp",
    singleLine = true,
    hint = res.string.media_search or "搜索文件名…",
    TintColor = primary,
    style = MDC_R.style.Widget_Material3_TextInputLayout_OutlinedBox_Dense,
  },

  {
    HorizontalScrollView,
    layout_width = "match",
    layout_height = "wrap",
    horizontalScrollBarEnabled = false,
    {
      LinearLayout,
      id = "toolBar",
      orientation = "horizontal",
      layout_width = "wrap",
      layout_height = "wrap",
      gravity = "center_vertical",
      paddingLeft = "8dp",
      paddingRight = "8dp",
      paddingBottom = "4dp",
      {
        MaterialButton,
        id = "btnSort",
        text = res.string.media_sort or "排序",
        layout_width = "wrap",
        layout_height = "wrap",
        minHeight = "36dp",
        textSize = "12sp",
        styleAttr = "?attr/borderlessButtonStyle",
        textColor = primary,
      },
      {
        MaterialButton,
        id = "btnSelectMode",
        text = res.string.media_select or "多选",
        layout_width = "wrap",
        layout_height = "wrap",
        minHeight = "36dp",
        textSize = "12sp",
        styleAttr = "?attr/borderlessButtonStyle",
        textColor = primary,
      },
      {
        MaterialButton,
        id = "btnSelectAll",
        text = res.string.media_select_all or "全选",
        layout_width = "wrap",
        layout_height = "wrap",
        minHeight = "36dp",
        textSize = "12sp",
        styleAttr = "?attr/borderlessButtonStyle",
        textColor = primary,
        visibility = "gone",
      },
      {
        MaterialButton,
        id = "btnDeleteSel",
        text = res.string.delete or "删除",
        layout_width = "wrap",
        layout_height = "wrap",
        minHeight = "36dp",
        textSize = "12sp",
        styleAttr = "?attr/borderlessButtonStyle",
        textColor = "?attr/colorError",
        visibility = "gone",
      },
      {
        MaterialButton,
        id = "btnShareSel",
        text = res.string.media_share or "分享",
        layout_width = "wrap",
        layout_height = "wrap",
        minHeight = "36dp",
        textSize = "12sp",
        styleAttr = "?attr/borderlessButtonStyle",
        textColor = primary,
        visibility = "gone",
      },
      {
        MaterialButton,
        id = "btnCopyPaths",
        text = res.string.media_copy_path or "复制路径",
        layout_width = "wrap",
        layout_height = "wrap",
        minHeight = "36dp",
        textSize = "12sp",
        styleAttr = "?attr/borderlessButtonStyle",
        textColor = primary,
        visibility = "gone",
      },
    },
  },

  {
    FrameLayout,
    layout_width = "match",
    layout_height = "0dp",
    layout_weight = 1,
    {
      SwipeRefreshLayout,
      id = "swipeRefresh",
      layout_width = "match",
      layout_height = "match",
      {
        RecyclerView,
        id = "fileList",
        layout_width = "match",
        layout_height = "match",
        paddingTop = "4dp",
        paddingBottom = "12dp",
        clipToPadding = false,
        overScrollMode = 2,
      },
    },
    {
      LinearLayout,
      id = "emptyView",
      orientation = "vertical",
      layout_width = "match",
      layout_height = "wrap",
      layout_gravity = "center",
      gravity = "center",
      padding = "32dp",
      visibility = "gone",
      {
        MaterialTextView,
        id = "emptyTitle",
        text = res.string.media_empty or "目录为空",
        textSize = "16sp",
        textStyle = "bold",
        textColor = "?attr/colorOnSurface",
        gravity = "center",
      },
      {
        MaterialTextView,
        id = "emptyHint",
        text = res.string.media_empty_hint or "崩溃日志与保存备份会出现在这里",
        textSize = "13sp",
        textColor = onVar,
        gravity = "center",
        layout_marginTop = "8dp",
      },
    },
  },
}
